const SettingsSync = React.memo(({ settings, setSettings, backend, networkFolders, setNetworkFolders, activityLogs, syncLogs, handleChange }) => {
    const refreshFolders = () => backend.request(JSON.stringify({action: 'get_mapped_folders'})).then(res => {
        const data = JSON.parse(res);
        setSettings(prev => ({...prev, mapped_folders: data.folders}));
        setNetworkFolders(data.network_folders);
    });
    const startSync = (action, message, progress = 5) => {
        setSettings(prev => ({...prev, git_status: 'syncing', sync_msg: message, sync_progress_pct: progress}));
        backend.request(JSON.stringify({action}));
    };

    return <>
        <div className="md:col-span-2 text-blue-400 font-bold uppercase tracking-widest text-xs border-b border-white/10 pb-1 mt-4">Sync Activity Log</div>
        <div className="md:col-span-2 bg-[#0c0c0f] border border-white/10 rounded-lg p-3 h-48 overflow-y-auto font-mono text-[10px] leading-relaxed custom-scrollbar shadow-inner relative">
            <div className="absolute top-2 right-2 text-gray-600 opacity-50"><i className="fas fa-circle text-[6px]"></i></div>
            {syncLogs.length === 0 ? <div className="text-gray-500 italic text-center py-4">No sync activity yet.</div> : syncLogs.map((log, i) => <div key={i} className="border-b border-white/5 py-1 text-gray-300">{log}</div>)}
        </div>

        <div className="md:col-span-2 text-blue-400 font-bold uppercase tracking-widest text-xs border-b border-white/10 pb-1 mt-4">Git Sync Status</div>
        <div className="md:col-span-2 flex flex-col gap-3">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4"><div className={`w-3 h-3 rounded-full ${settings.git_status === 'connected' ? 'bg-green-500 animate-pulse' : settings.git_status === 'error' ? 'bg-red-500' : settings.git_status === 'syncing' ? 'bg-yellow-500 animate-pulse' : 'bg-gray-500'}`}></div><span className="text-sm font-medium text-gray-300">{settings.git_status === 'connected' ? 'Connected to GitHub' : settings.git_status === 'syncing' ? 'Syncing...' : settings.git_status === 'error' ? 'Sync Error' : 'Not Connected'}</span></div>
                <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest bg-black/40 px-3 py-1 rounded border border-white/10"><i className="fas fa-clock mr-1"></i> Next Auto-Sync: <span className="text-blue-400 ml-1">{settings.sync_enabled && settings.sync_interval ? `~${Math.round(settings.sync_interval / 60)} min` : 'Disabled'}</span></div>
            </div>
            {settings.git_status === 'syncing' && <div className="w-full bg-black/40 h-2 rounded-full overflow-hidden border border-white/10 my-2"><div className="bg-blue-500 h-full transition-all duration-300 ease-out" style={{width: `${settings.sync_progress_pct || 100}%`}}></div></div>}
            <div className="flex gap-3">
                <button onClick={() => {
                    setSettings(prev => ({...prev, git_status: 'syncing', sync_msg: 'Verifying connection...', sync_progress_pct: 10}));
                    backend.request(JSON.stringify({action: 'get_sync_status'})).then(res => { const data = JSON.parse(res); setSettings(prev => ({...prev, git_status: data.enabled ? 'connected' : 'error', git_last_sync: new Date().toLocaleString(), sync_msg: data.enabled ? 'Connection verified' : 'Check configuration', sync_progress_pct: 100})); }).catch(() => setSettings(prev => ({...prev, git_status: 'error', sync_msg: 'Backend connection failed', sync_progress_pct: 0})));
                }} className="glass-button px-4 py-2 rounded text-xs font-bold tracking-widest text-white uppercase bg-blue-600/30 border-blue-500/50 hover:bg-blue-600"><i className="fas fa-satellite-dish mr-2"></i> Verify Connection</button>
                <button onClick={() => startSync('sync_now', 'Initiating sync process...')} className="glass-button px-6 py-2 rounded text-xs font-bold tracking-widest text-white uppercase bg-green-600/30 border-green-500/50 hover:bg-green-600 shadow-[0_0_10px_rgba(34,197,94,0.2)]"><i className="fas fa-sync-alt mr-2"></i> Force Sync Now</button>
            </div>
            <div className="flex flex-col mt-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 flex justify-between"><span>Terminal Output</span><span><i className="fas fa-terminal mr-1"></i> System Bridge</span></label>
                <div className="bg-[#0c0c0f] border border-white/10 rounded-lg p-3 h-32 overflow-y-auto font-mono text-[10px] leading-relaxed custom-scrollbar shadow-inner relative">
                    <div className="absolute top-2 right-2 text-gray-600 opacity-50"><i className="fas fa-circle text-[6px]"></i></div><div className="text-gray-500 mb-1">$ systemctl status sync_manager</div>
                    <div className="text-gray-300"><span className="text-blue-400">Device ID:</span> {settings.device_id || 'Not set'}</div><div className="text-gray-300"><span className="text-blue-400">Target Repo:</span> {settings.sync_repo_url ? settings.sync_repo_url.split('/').slice(-2).join('/') : 'Not configured'}</div><div className="text-gray-300 mb-2"><span className="text-blue-400">Last Sync:</span> {settings.git_last_sync || 'Never'}</div>
                    {settings.sync_msg && <div className={`mt-2 p-2 border-l-2 rounded-r-md ${settings.git_status === 'error' ? 'bg-red-900/20 border-red-500 text-red-400' : settings.git_status === 'syncing' ? 'bg-yellow-900/20 border-yellow-500 text-yellow-400' : 'bg-green-900/20 border-green-500 text-green-400'}`}>{settings.git_status === 'syncing' && <i className="fas fa-spinner fa-spin mr-2"></i>}{settings.git_status === 'error' && <i className="fas fa-times-circle mr-2"></i>}{settings.git_status === 'connected' && <i className="fas fa-check-circle mr-2"></i>}{settings.sync_msg}</div>}
                </div>
            </div>
        </div>

        <div className="md:col-span-2 text-red-500 font-bold uppercase tracking-widest text-xs border-b border-red-500/30 pb-1 mt-6">Danger Zone</div>
        <div className="md:col-span-2 grid grid-cols-1 md:grid-cols-3 gap-4 p-4 bg-red-900/10 border border-red-500/20 rounded-lg">
            <div className="flex flex-col gap-3"><div className="flex flex-col"><span className="text-xs font-bold text-red-400">1. Master Overwrite (Force Push)</span><span className="text-[10px] text-gray-400 leading-relaxed mt-1">Make THIS device the absolute Master. Forces this data to the cloud and deletes conflicting nodes.</span></div><button onClick={() => { if(confirm("WARNING: This will make this device the absolute master and wipe conflicting remote data. Continue?")) startSync('force_sync_now', 'Initiating MASTER OVERWRITE...', 10); }} className="glass-button px-4 py-3 mt-auto rounded text-xs font-bold tracking-widest text-white uppercase bg-red-600/50 border-red-500/50 hover:bg-red-600 shadow-[0_0_15px_rgba(239,68,68,0.3)] w-full transition-all"><i className="fas fa-upload mr-2"></i> Force Push as Master</button></div>
            <div className="flex flex-col gap-3"><div className="flex flex-col"><span className="text-xs font-bold text-yellow-400">2. Hard Clone (Force Pull)</span><span className="text-[10px] text-gray-400 leading-relaxed mt-1">Wipe THIS device's database completely and clone an exact 1:1 copy of the Master Node.</span></div><button onClick={() => { if(confirm("DANGER: This will completely WIPE this PC's local database and download the master copy from Git. Proceed?")) startSync('hard_clone_remote', 'Initiating HARD CLONE...', 10); }} className="glass-button px-4 py-3 mt-auto rounded text-xs font-bold tracking-widest text-white uppercase bg-yellow-600/50 border-yellow-500/50 hover:bg-yellow-600 shadow-[0_0_15px_rgba(234,179,8,0.3)] w-full transition-all"><i className="fas fa-download mr-2"></i> Wipe & Clone Master</button></div>
            <div className="flex flex-col gap-3"><div className="flex flex-col"><span className="text-xs font-bold text-red-600">3. Force Reset All Data</span><span className="text-[10px] text-gray-400 leading-relaxed mt-1">Completely wipe ALL local data: database, config, and Git sync repo. Sync settings (repo URL, token) are preserved. App will reload.</span></div><button onClick={() => {
                if(confirm("DANGER: This will permanently delete ALL local data, including your database, configuration, and Git sync repo. This action cannot be undone. Continue?")) { setSettings(prev => ({...prev, git_status: 'syncing', sync_msg: 'Resetting all data...', sync_progress_pct: 10})); backend.request(JSON.stringify({action: 'force_reset_all_data'})).then(res => { const data = JSON.parse(res); if (data.status === 'success') { let url = window.location.href; if (url.endsWith('/')) url += 'index.html'; else if (url.endsWith('Modular') || url.endsWith('shadow_os_cache')) url += '/index.html'; else if (!url.includes('index.html') && !url.match(/\.html?$/)) url = url + (url.endsWith('/') ? '' : '/') + 'index.html'; window.location.replace(url); } else alert('Reset failed: ' + data.message); }); }
            }} className="glass-button px-4 py-3 mt-auto rounded text-xs font-bold tracking-widest text-white uppercase bg-red-700/50 border-red-600/50 hover:bg-red-700 shadow-[0_0_15px_rgba(239,68,68,0.3)] w-full transition-all"><i className="fas fa-trash-alt mr-2"></i> Wipe All Data</button></div>
        </div>

        <div className="md:col-span-2 text-blue-400 font-bold uppercase tracking-widest text-xs border-b border-white/10 pb-1 mt-4">System Activity Ledger</div>
        <div className="md:col-span-2 bg-[#0c0c0f] border border-white/10 rounded-lg p-3 h-48 overflow-y-auto font-mono text-[10px] leading-relaxed custom-scrollbar shadow-inner relative"><table className="w-full text-left"><thead className="sticky top-0 bg-[#0c0c0f] text-gray-500 pb-2"><tr><th className="w-1/4 pb-2">Timestamp</th><th className="w-1/4 pb-2">Module</th><th className="w-1/2 pb-2">Action</th></tr></thead><tbody>{activityLogs && activityLogs.length > 0 ? activityLogs.map((log, i) => <tr key={i} className="border-b border-white/5 hover:bg-white/5 transition-colors text-gray-300"><td className="py-1">{new Date(log.timestamp).toLocaleString()}</td><td className="py-1 text-blue-400">[{log.module}]</td><td className="py-1">{log.description}</td></tr>) : <tr><td colSpan="3" className="text-gray-500 italic py-2 text-center">No activity logged yet.</td></tr>}</tbody></table></div>

        <div className="md:col-span-2 text-blue-400 font-bold uppercase tracking-widest text-xs border-b border-white/10 pb-1 mt-4">File & Device Sync Configuration</div>
        <div className="md:col-span-2 flex flex-col gap-3">
            <div className="flex items-center gap-4"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Device ID</label><span className="text-xs font-mono text-blue-400 bg-black/40 px-3 py-1 rounded border border-white/10">{settings.device_id || 'Loading...'}</span></div>
            <div className="flex items-center gap-4"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Enable Auto-Sync</label><input type="checkbox" checked={settings.sync_enabled || false} onChange={e => handleChange('sync_enabled', e.target.checked)} className="w-5 h-5 rounded bg-black/40 border border-white/20 accent-blue-500" /></div>
            <div className="flex flex-col gap-1"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">GitHub Repository URL</label><input type="text" value={settings.sync_repo_url || ''} onChange={e => handleChange('sync_repo_url', e.target.value)} className="glass-input p-2.5 rounded text-sm w-full" placeholder="https://github.com/username/repo.git" /></div>
            <div className="flex flex-col gap-1"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">GitHub Token Status</label><div className="flex items-center gap-3 p-2 bg-black/40 rounded border border-white/10">{settings.has_token ? <span className="text-green-400"><i className="fas fa-check-circle mr-2"></i> PAT secured in OS Environment variables</span> : <span className="text-yellow-400"><i className="fas fa-exclamation-triangle mr-2"></i> Token not set. Add GITHUB_TOKEN to .env file</span>}</div></div>
            <div className="flex flex-col gap-1"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Auto-Sync Interval (seconds)</label><input type="number" value={settings.sync_interval || 3600} onChange={e => handleChange('sync_interval', parseInt(e.target.value))} className="glass-input p-2.5 rounded text-sm w-32" /></div>
        </div>

        <div className="md:col-span-2 flex flex-col gap-2 mt-2"><label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Mapped Folders (Cross-Device P2P Share)</label>
            <div className="flex gap-2"><input type="text" id="folder-input" placeholder="C:/Users/... or /Users/..." className="glass-input p-2.5 rounded text-sm flex-grow" /><button onClick={() => { const input = document.getElementById('folder-input'); if (input.value) backend.request(JSON.stringify({action: 'map_folder', path: input.value})).then(() => { input.value = ''; refreshFolders(); }); }} className="glass-button px-4 py-2 rounded text-xs font-bold text-green-300 uppercase border border-green-500/30 hover:bg-green-900/30"><i className="fas fa-plus mr-1"></i> Map Folder</button><button onClick={() => backend.request(JSON.stringify({action: 'open_folder_dialog'})).then(res => { const data = JSON.parse(res); if (data.path) document.getElementById('folder-input').value = data.path; })} className="glass-button px-4 py-2 rounded text-xs font-bold text-blue-300 uppercase border border-blue-500/30 hover:bg-blue-900/30"><i className="fas fa-folder-open mr-1"></i> Browse OS</button></div>
            <div className="flex flex-wrap gap-2 mt-2 max-h-40 overflow-y-auto p-3 bg-[#0c0c0f] rounded-lg border border-white/5 shadow-inner">{settings.mapped_folders && settings.mapped_folders.length > 0 ? settings.mapped_folders.map((path, i) => <span key={i} className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-full text-xs border border-white/10 group hover:bg-white/20 transition-all cursor-default"><i className="fas fa-folder text-yellow-400 text-xs shadow-sm"></i><span className="font-mono text-gray-300 truncate max-w-xs" title={path}>{path}</span><button onClick={() => backend.request(JSON.stringify({action: 'unmap_folder', path})).then(refreshFolders)} className="text-red-400 hover:text-red-300 opacity-0 group-hover:opacity-100 transition-all ml-1"><i className="fas fa-times-circle"></i></button></span>) : <span className="text-xs text-gray-500 italic">No folders mapped. Data will be automatically packaged and pushed to the Git network.</span>}</div>
        </div>

        <div className="md:col-span-2 text-blue-400 font-bold uppercase tracking-widest text-xs border-b border-white/10 pb-1 mt-4">Cluster Topology & Sync</div>
        <div className="md:col-span-2 flex flex-col gap-4 bg-[#0c0c0f] p-4 rounded-lg border border-white/10"><div className="flex justify-between items-center"><div className="flex items-center gap-3"><div className={`w-3 h-3 rounded-full ${settings.git_status === 'connected' ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`}></div><span className="text-xs font-bold text-white uppercase tracking-widest">{settings.git_status === 'connected' ? 'Connected to Git Cluster' : 'Sync Disconnected'}</span></div><div className="text-[10px] font-mono text-blue-400 bg-blue-950/40 px-3 py-1 rounded border border-blue-500/30">Current Node: <span className="font-bold text-white">{settings.device_id ? settings.device_id.substring(0, 12) : 'Loading...'}</span></div></div>
            <div className="flex flex-col gap-2 p-3 bg-black/40 rounded border border-white/5"><div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Cluster Master Authority</div><div className="flex justify-between items-center"><div className="text-xs text-gray-300 font-mono">Master ID: <span className="text-yellow-400 font-bold">{settings.master_id ? settings.master_id.substring(0, 16) + '...' : 'None Assigned (Decentralized)'}</span></div><button onClick={() => { if(confirm("Promote this PC as the absolute Cluster Master? All other nodes will pull from this state.")) startSync('force_sync_now', 'Promoting to Master...', 20); }} className="glass-button px-4 py-1.5 rounded text-[10px] font-bold tracking-widest text-white uppercase bg-blue-600/40 border-blue-500/50 hover:bg-blue-600"><i className="fas fa-crown mr-1 text-yellow-400"></i> Promote This PC to Master</button></div></div>
            <div className="flex gap-3"><button onClick={() => startSync('sync_now', 'Syncing with cluster...')} className="glass-button px-5 py-2 rounded text-xs font-bold tracking-widest text-white uppercase bg-green-600/30 border-green-500/50 hover:bg-green-600"><i className="fas fa-sync-alt mr-2"></i> Standard Sync Now</button><span className="text-[10px] text-gray-500 self-center">Merges changes or pulls from Master depending on your node role.</span></div>
        </div>

        <div className="md:col-span-2 text-yellow-400 font-bold uppercase tracking-widest text-xs border-b border-yellow-500/30 pb-1 mt-4">Discovered Database Peer Nodes (K-Cluster)</div>
        <div className="md:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-3">{networkFolders && networkFolders.length > 0 ? networkFolders.map((f, i) => <div key={i} className="flex flex-col p-3 bg-[#0c0c0f] border border-white/10 rounded-lg shadow-md relative overflow-hidden"><div className={`absolute top-0 left-0 w-1 h-full ${f.is_local ? 'bg-blue-500' : 'bg-purple-500'}`}></div><div className="flex justify-between items-center mb-2 pl-2"><span className="text-xs font-bold text-white uppercase tracking-widest font-mono">Node {f.device_id.substring(0, 8)} {f.is_local ? '(This PC)' : ''}</span><span className="text-[9px] text-gray-400 font-mono">{f.last_update}</span></div><div className="flex justify-between items-center text-[10px] text-gray-400 font-mono pl-2"><span><i className="fas fa-file-archive mr-1"></i>{f.file_count} files</span></div><div className="pl-2 mt-2">{f.is_local ? <span className="text-[10px] text-blue-400 italic">Local Database Node</span> : <button onClick={() => { if(confirm(`DANGER: Completely wipe this PC's database and hard-clone all settings, goals, and pomodoro data from Node ${f.device_id.substring(0,8)}?`)) { setSettings(prev => ({...prev, git_status: 'syncing', sync_msg: `Cloning Node ${f.device_id.substring(0,8)}...`, sync_progress_pct: 10})); backend.request(JSON.stringify({action: 'hard_clone_remote', target_device: f.device_id})); } }} className="w-full py-2 bg-yellow-600/30 hover:bg-yellow-600 border border-yellow-500/50 rounded text-[10px] font-bold uppercase tracking-widest text-yellow-300 hover:text-white transition-all shadow"><i className="fas fa-file-download mr-1"></i> Hard Clone DB From This Node</button>}</div></div>) : <div className="text-xs text-gray-500 italic p-3 bg-[#0c0c0f] rounded-lg border border-white/5 col-span-2 text-center">No peer nodes found in Git repository yet. Run "Standard Sync Now" to discover nodes.</div>}</div>
    </>;
});
